#:schema node_modules/wrangler/config-schema.json
name = "products-api"
main = "src/index.ts"
compatibility_date = "2024-05-24"
compatibility_flags = ["nodejs_compat"]

services = [
  { binding = "WORKER", service = "products-service" }
]
